name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
        gemfile:
          - "rails6.0"
          - "rails6.1"
          - "rails7.0"
        include:
          - {ruby: "2.6", gemfile: "rails4.2"}
          - {ruby: "2.6", gemfile: "rails5.0"}
          - {ruby: "2.6", gemfile: "rails5.1"}
          - {ruby: "2.6", gemfile: "rails5.2"}
          - {ruby: "2.7", gemfile: "rails5.0"}
          - {ruby: "2.7", gemfile: "rails5.1"}
          - {ruby: "2.7", gemfile: "rails5.2"}
    name: ruby${{ matrix.ruby }} ${{ matrix.gemfile }} rake spec
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    - run: bundle exec rake spec
      env:
        BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile

  specs_successful:
    name: Specs passing?
    needs: specs
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.specs.result == 'success' }}
          then
            echo "All specs passed"
          else
            echo "Some specs failed"
            false
          fi
